-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 09:36:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `usuario` VARCHAR(85) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(125) NOT NULL,
  `cidade` VARCHAR(125) NOT NULL,
  `cep` CHAR(8) NULL,
  `estado` CHAR(2) NULL,
  `pais` VARCHAR(55) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco_Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco_Estoque` (
  `estoque` INT NOT NULL,
  `endereco` INT NOT NULL,
  PRIMARY KEY (`estoque`, `endereco`),
  CONSTRAINT `fk_Estoque_has_Endereco_Estoque1`
    FOREIGN KEY (`estoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Endereco_Endereco1`
    FOREIGN KEY (`endereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estoque_has_Endereco_Endereco1_idx` ON `mydb`.`Endereco_Estoque` (`endereco` ASC) VISIBLE;

CREATE INDEX `fk_Estoque_has_Endereco_Estoque1_idx` ON `mydb`.`Endereco_Estoque` (`estoque` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco_Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco_Fornecedor` (
  `endereco` INT NOT NULL,
  `fornecedor` INT NOT NULL,
  PRIMARY KEY (`endereco`, `fornecedor`),
  CONSTRAINT `fk_Endereco_has_Fornecedor_Endereco1`
    FOREIGN KEY (`endereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Endereco_has_Fornecedor_Fornecedor1_idx` ON `mydb`.`Endereco_Fornecedor` (`fornecedor` ASC) VISIBLE;

CREATE INDEX `fk_Endereco_has_Fornecedor_Endereco1_idx` ON `mydb`.`Endereco_Fornecedor` (`endereco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `nome` VARCHAR(125) NOT NULL,
  `capacidade` INT NOT NULL,
  `cliente` INT NOT NULL,
  `fornecedor` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  CONSTRAINT `fk_Estoque_Cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Fornecedor1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estoque_Cliente_idx` ON `mydb`.`Estoque` (`cliente` ASC) VISIBLE;

CREATE INDEX `fk_Estoque_Fornecedor1_idx` ON `mydb`.`Estoque` (`fornecedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(85) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipoProduto` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecimento_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecimento_Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecimento_Produto` (
  `produto` INT NOT NULL,
  `fornecedor` INT NOT NULL,
  `fornecimento` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`produto`, `fornecedor`),
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`produto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` ON `mydb`.`Fornecimento_Produto` (`fornecedor` ASC) VISIBLE;

CREATE INDEX `fk_Produto_has_Fornecedor_Produto1_idx` ON `mydb`.`Fornecimento_Produto` (`produto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `nome` VARCHAR(355) NOT NULL,
  `descricao` VARCHAR(1225) NULL,
  `quantidade` INT NOT NULL,
  `codigoBarras` VARCHAR(64) NULL,
  `unidade` VARCHAR(45) NOT NULL,
  `fabricacao` DATE NULL,
  `validade` DATE NULL,
  `marca` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `estoque` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  CONSTRAINT `fk_Produto_Estoque1`
    FOREIGN KEY (`estoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_Estoque1_idx` ON `mydb`.`Produto` (`estoque` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
